name: holo_cart
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.3
  flutter_screenutil: ^5.9.3
  animated_splash_screen: ^1.3.0
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  animated_rating_bar: ^0.0.8
  flutter_credit_card: ^4.1.0
  flutter_svg: ^2.0.17
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  retrofit_generator: ^9.2.0
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  meta: ^1.15.0
  bloc: ^9.0.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  email_otp: ^3.0.2
  flutter_otp_text_field: ^1.5.1+1
  loading_animation_widget: ^1.3.0
  salomon_bottom_bar: ^3.3.2
  sqflite: ^2.4.1
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  device_preview: ^1.2.0
  model_viewer_plus: ^1.9.2
  country_picker: ^2.0.27
  custom_rating_bar: ^3.0.0
  stripe_android: "10.0.0"
  flutter_stripe: ^10.0.0
  flutter_paypal_payment: ^1.0.7
  flutter_dotenv: ^5.1.0
  fluttertoast: ^8.2.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/models/
    - .env
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
  